Fix to issue: GAP doesn't collect words properly with "-"
xnl-h4ck3r/GAP-Burp-Extension pull request #21
Opened 2023-07-14 22:47 UTC by bebiksior

I've noticed that GAP doesn't collect words properly from URL paths that look like this:
`/api/custom-polls/home/pending-draft-polls-count`

Old version collects only the following words:
`api,custom,pools,home,pending,draft,polls,count`

It should collect the following words:
`api,custom-pools,custom,pools,home,pending-draft-polls-count,pending,draft,count`

I've made a fix for this issue, although it needs further testing.

2023-07-21 20:04 UTC, xnl-h4ck3r requested changes
Hey @bebiksior . Thanks for the pull request.
This looks like it works great, although I don't think we need the separate conversion from set to list etc.  You could just change the one line to `words = set(re.compile(r"[\:/?=\-&#]+", re.UNICODE).split(path) + path.split('/'))`

Coul you change it to that, and double check that's fine?
Also, I just realised that path words also need to be split by comma `,`, e.g. I have seen URLs like `http://www.chewy.com/cat/food-treats-387/FoodFlavor_facet:Duck,FoodForm_facet:Wet%20Food,brand_facet:Addiction?noidx=1`
Do you know how we can also split on comma too?

2023-07-24 11:47 UTC, xnl-h4ck3r commented
Hey @bebiksior 
To have the fix you suggested and also deal with commas to split on those, we could do this:
```
            # Split the URL on /
            words = set(re.compile(r"[\:/?=\-&#]+", re.UNICODE).split(path) + path.split('/'))
            temp = []
            for x in words:
                temp.extend(x.split(","))
            words = set(temp)
```
Maybe there's a better way, not sure. What do you thik? If you want to change the pull request to this, then I'll accept it and gte it in there (or if there's a better more efficient way, even better).
I'm releasing a big update to GAP in a few weeks so I can inculde this in there anyway if you don't get around to changing the pull request.
Thanks again!

2023-07-24 12:37 UTC, bebiksior commented
Hey! I don't see a better way to do this. I updated the code in the pull request. 
Thanks for making GAP :-)

2023-07-24 18:08 UTC, xnl-h4ck3r approved these changes
Great!

2023-07-24 18:09 UTC, merged